changelog:
  exclude:
    authors:
      - dependabot[bot]
      - renovate[bot]
  categories:
    - title: ⚡️ Breaking Changes
      labels:
        - breaking
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
    - title: 🔨 Maintenance
      labels:
        - maintenance
        - refactor
    - title: Misc
      labels:
        - "*"