#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
#
# Runs the OAuth 1.0 three-legged flow against the oauth1 service in
# compose.yml and writes the token credentials it issues into
# samples/OAuthHttpClientSample/appsettings.Development.json, which is
# gitignored.
#
#   scripts/oauth1-token.sh          walk through it, approving in a browser
#   scripts/oauth1-token.sh --ci     approve over HTTP, no human, no browser
#
# CI=true in the environment implies --ci.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
AUTHORIZER_DIR="$REPO_ROOT/samples/OAuthInteractiveConsoleAuthorizer"
TARGET_CONFIG="$REPO_ROOT/samples/OAuthHttpClientSample/appsettings.Development.json"

# Inside the dev container the service is reachable by name; from the host it is
# published on 5001, because 5000 is taken by AirPlay Receiver on macOS.
OAUTH1_URL="${OAUTH1_URL:-http://oauth1:5000}"
RESOURCE_OWNER="${RESOURCE_OWNER:-example-user}"

NON_INTERACTIVE=0
[[ "${CI:-}" == "true" || "${1:-}" == "--ci" ]] && NON_INTERACTIVE=1

WORK_DIR=$(mktemp -d)
COOKIE_JAR="$WORK_DIR/cookies"
SAMPLE_LOG="$WORK_DIR/authorizer.log"
SAMPLE_INPUT="$WORK_DIR/verification-code"
cleanup() {
  [[ -n "${SAMPLE_PID:-}" ]] && kill "$SAMPLE_PID" 2>/dev/null
  rm -rf "$WORK_DIR"
}
trap cleanup EXIT

if (( NON_INTERACTIVE )); then
  # The library's pauses and prompts all read stdin, which nothing will answer.
  banner() { :; }
  pause()  { :; }
  _clear() { :; }
fi

banner "OAuth 1.0 token credentials"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Check the OAuth 1.0 server"
say "Looking for the oauth1 service at $OAUTH1_URL"
if ! curl -sf --max-time 5 "$OAUTH1_URL/api/health" >/dev/null; then
  warn "no answer from $OAUTH1_URL"
  note "start it with: docker compose up -d"
  note "from the host rather than the dev container, use: OAUTH1_URL=http://localhost:5001 $0"
  exit 1
fi
say "Server is up."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Sign in as the resource owner"
say "The test server takes any username and creates a session; no password."
curl -sf -c "$COOKIE_JAR" -d "username=$RESOURCE_OWNER" "$OAUTH1_URL/" -o /dev/null
say "Signed in as $RESOURCE_OWNER."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Run the three-legged flow"
say "Starting the interactive authorizer sample; it requests temporary"
say "credentials and asks for a verification code."

mkfifo "$SAMPLE_INPUT"
( cd "$AUTHORIZER_DIR" && OAuth__BaseAddress="$OAUTH1_URL" dotnet run --verbosity quiet ) \
  < "$SAMPLE_INPUT" > "$SAMPLE_LOG" 2>&1 &
SAMPLE_PID=$!
exec 3> "$SAMPLE_INPUT"

# Both the container's xdg-open shim and the library's own fallback print the
# authorization URI, so it turns up in the sample's output either way.
AUTHORIZE_URL=""
for _ in $(seq 1 120); do
  AUTHORIZE_URL=$(grep -oE 'https?://[^ ]*oauth_token=[^ ]+' "$SAMPLE_LOG" | head -n1 || true)
  [[ -n "$AUTHORIZE_URL" ]] && break
  kill -0 "$SAMPLE_PID" 2>/dev/null || break
  sleep 1
done
if [[ -z "$AUTHORIZE_URL" ]]; then
  warn "the sample never printed an authorization URL"
  note "its output:"
  sed 's/^/    /' "$SAMPLE_LOG"
  exit 1
fi
REQUEST_TOKEN=${AUTHORIZE_URL##*oauth_token=}
REQUEST_TOKEN=${REQUEST_TOKEN%%&*}

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Authorize and collect the credentials"
if (( NON_INTERACTIVE )); then
  # oauth_callback is 'oob', so authorizing returns the verifier in the body
  # rather than redirecting.
  VERIFIER=$(curl -sf -b "$COOKIE_JAR" \
    -d "oauth_token=$REQUEST_TOKEN" -d "confirm=yes" \
    "$OAUTH1_URL/oauth/authorize" | sed -n 's/.*oauth_verifier=\([^&]*\).*/\1/p')
  if [[ -z "$VERIFIER" ]]; then
    warn "the server did not return a verifier"
    exit 1
  fi
  say "Approved over HTTP; verifier $VERIFIER"
else
  open_url "$AUTHORIZE_URL"
  step "Sign in as any username if asked, then click 'yes'."
  step "The page then shows oauth_token=...&oauth_verifier=... - copy the verifier."
  ask VERIFIER "Paste the verification code:"
fi

printf '%s\n' "$VERIFIER" >&3
exec 3>&-
wait "$SAMPLE_PID" || true
unset SAMPLE_PID

TOKEN_ID=$(sed -n 's/^Key: //p' "$SAMPLE_LOG" | tail -n1)
TOKEN_SECRET=$(sed -n 's/^Secret: //p' "$SAMPLE_LOG" | tail -n1)
if [[ -z "$TOKEN_ID" || -z "$TOKEN_SECRET" ]]; then
  warn "no token credentials in the sample's output"
  sed 's/^/    /' "$SAMPLE_LOG"
  exit 1
fi

cat > "$TARGET_CONFIG" <<JSON
{
  "OAuth": {
    "TokenId": "$TOKEN_ID",
    "TokenSecret": "$TOKEN_SECRET"
  }
}
JSON
printf '  %s✓ wrote%s TokenId and TokenSecret → %s\n' "$GREEN" "$RESET" "${TARGET_CONFIG#"$REPO_ROOT"/}"

if (( NON_INTERACTIVE )); then
  printf '\n  OAuthHttpClientSample is ready to run.\n\n'
else
  finish
  note "run the sample:  cd samples/OAuthHttpClientSample && dotnet run"
fi
