name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allow manually triggering the workflow.
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
      - name: Build
        run: |
          dotnet --info
          dotnet build -c Release
      - name: Test
        run: |
          dotnet test --collect:"XPlat Code Coverage"
          dotnet tool restore
          dotnet tool run reportgenerator
          [[ -f "./coverage/Summary.txt" ]] && cat "./coverage/Summary.txt"
      - uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
