name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allow manually triggering the workflow.
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 10
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            8.0.x
      - name: Build
        run: |
          dotnet --info
          dotnet build -c Release
      - name: Test
        run: |
          dotnet test --collect:"XPlat Code Coverage"
          dotnet tool restore
          dotnet tool run reportgenerator "-reports:**/coverage.cobertura.xml" "-targetdir:coverlet/reports" "-reporttypes:Cobertura"
      - uses: codecov/codecov-action@v4
        with:
          name: unittests-${{ matrix.os }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
