name: CD

on:
  push:
    branches:
      - main
      - "release/*"
    tags:
      - "*"

permissions: read-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Build packages
        run: |
          dotnet --info
          dotnet pack -c Release -o packages
      - name: Publish to NuGet.org
        run: dotnet nuget push "packages/*.nupkg" -k ${{ secrets.NUGET_AUTH_TOKEN }} -s https://api.nuget.org/v3/index.json --skip-duplicate
