name: CD

on:
  push:
    branches:
      - main
      - "release/*"
    tags:
      - "*"

jobs:
  deploy:
    if: secrets.NUGET_API_KEY
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Build packages
        run: |
          dotnet --info
          dotnet pack -c Release -o packages
      - name: Push to NuGet.org
        run: dotnet nuget push packages/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
